#!/bin/sh

#picom --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 3 &
picom &                                                                     # transparency
sxhkd &                                                                     # hotkeys
xsetroot -cursor_name left_ptr &                                            # keep cursor the same for bg focus
libinput-gestures-setup restart &                                           # three-finger swipe for desktop switching
fc-cache &                                                                  # reload font cache for polybar
xbindkeys &                                                                 # disable middle mouse button paste
xset -b &                                                                   # disable errorbell
imwheel &                                                                   # increase mouse scroll speed

# udevadm monitor
thunderbolt_dir=/sys/devices/pci0000:00/0000:00:1d.4/0000:03:00.0/0000:04:00.0/0000:05:00.0/domain0/0-0/0-1

if [[ -d $thunderbolt_dir ]]; then
    # Use laptop monitor if veritical monitor is present
    if xrandr -q | rg -i 'dp-2 connected 1440' &>/dev/null; then bspc monitor DP-1 -d I II III IV V
        bspc monitor DP-1 -d I II III IV V &
        bspc monitor DP-2 -d VI VII VIII IX X &
        bspc monitor eDP-1 -d XI XI XIII XIV XV &
    else
        # need to remove laptop monitor
        bspc monitor eDP-1 -r &
        bspc monitor DP-1 -d I II III IV V &
        bspc monitor DP-2 -d VI VII VIII IX X &
    fi
else
    bspc monitor -d I II III IV V
fi

#color=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
#color2=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)

# Border
bspc config border_width                                    3
bspc config window_gap                                      20
bspc config top_padding                                     50        #30
bspc config bottom_padding                                  10        #30
bspc config left_padding                                    0
bspc config right_padding                                   0

bspc config normal_border_color                             \#312e30
bspc config active_border_color                             \#312e30
bspc config focused_border_color                            \#FFFFFF
bspc config presel_feedback_color                           \#2a2829

bspc config split_ratio                                     0.50
bspc config borderless_monocle                              true
bspc config gapless_monocle                                 true
bspc config focus_follows_pointer                           true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a discord state=pseudo_tiled focus=on
bspc rule -a Google-chrome desktop='^2' focus=on
bspc rule -a Zathura state=tiled focus=on

# if [[ -d $thunderbolt_dir ]]; then
#     bspc rule -a Brave-browser desktop='^6' focus=on
# else
#     bspc rule -a Brave-browser desktop='^6' focus=on
# fi

#bspc rule -a feh state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Set wallpaper randomly
random_image=$(ls $WALLPAPER_DIR | shuf -n 1);
random_backend=$(shuf -n 1 -e wal haishoku colorthief); \
feh --bg-fill "$WALLPAPER_DIR/$random_image" &
eval "set -- $(sed 1d "$HOME/.fehbg")" &
wal -qn -i $4 --backend $random_backend &

dunst &                                                                     # notifications
wal -i $random_image &                                                   # set wallpaper and colorscheme
$HOME/.config/polybar/themes/blocks/launch.sh &                             # start polybar
