#!/bin/sh

#picom --experimental-backends --backend glx --blur-method dual_kawase --blur-strength 3 &
picom &                                                                     # transparency
sxhkd &                                                                     # hotkeys
xsetroot -cursor_name left_ptr &                                            # keep cursor the same for bg focus
libinput-gestures-setup restart &                                           # three-finger swipe for desktop switching
fc-cache &                                                                  # reload font cache for polybar
xbindkeys &                                                                 # disable middle mouse button paste
xset -b &                                                                   # disable errorbell

bspc monitor -d I II III IV V

#color=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
#color2=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)

# Border
bspc config border_width                                    3
bspc config window_gap                                      20
bspc config top_padding                                     50        #30
bspc config bottom_padding                                  10        #30
bspc config left_padding                                    0
bspc config right_padding                                   0

bspc config normal_border_color                             \#312e30
bspc config active_border_color                             \#b1942b
bspc config focused_border_color                            \#FFFFFF
bspc config presel_feedback_color                           \#2a2829

bspc config split_ratio                                     0.52
bspc config borderless_monocle                              true
bspc config gapless_monocle                                 true
bspc config focus_follows_pointer                           true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a discord desktop='^3' state=pseudo_tiled focus=on
bspc rule -a Google-chrome desktop='^2' focus=on
bspc rule -a Brave-browser desktop='^2' focus=on
bspc rule -a Zathura state=tiled focus=on
#bspc rule -a feh state=floating
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Set wallpaper randomly
random_image=$(ls $WALLPAPER_DIR | shuf -n 1);

feh --bg-fill "$WALLPAPER_DIR/$random_image";
    eval "set -- $(sed 1d "$HOME/.fehbg")"; \
    wal -n -i $4;

dunst &                                                                     # notifications

# Start polybar
$HOME/.config/polybar/themes/blocks/launch.sh &
